/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SheldonJ99 (https://sketchfab.com/sheldonj99)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mazda-rx7-stylised-898e9be8c8964f6298188a2901216e80
Title: Mazda RX7 Stylised
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useMemo, useRef } from "react";

export function Car({ effectSettings, ...props }) {
  const { nodes, materials } = useGLTF("/car.glb");
  const uniforms = useMemo(() => ({ uPixelRatio: { value: 3.0 } }), []);
  const matARef = useRef(null);
  const matBRef = useRef(null);

  const vertex =
    /* glslx */
    `
  varying vec3 vNormal;
  void main() {

    vNormal = normalize(normalMatrix * normal); 

    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
}
  `;

  const fragment =
    /* glslx */
    `
  varying vec3 vNormal;
  uniform float uPixelRatio;

  void main() {

     vec3 dirlight = normalize(vec3(1.0, 1.0, 1.0));
    
     float diffuse = max(dot(vNormal, dirlight), 0.0);
     float ambient = 0.2;
     float brightness = diffuse + ambient;

     const mat4 bayer = mat4(
      0.0, 12.0, 3.0, 15.0,
      8.0, 3.0, 11.0, 7.0,
      2.0, 14.0,1.0, 13.0,
      10.0, 6.0, 9.0, 5.0
     ) / 16.0;

     vec2 coord = floor(gl_FragCoord.xy / uPixelRatio);

    int x = int(mod(coord.x, 4.0));
    int y = int(mod(coord.y, 4.0));

    float threshold = bayer[x][y];

    float dither = step(threshold, brightness);

    gl_FragColor = vec4(vec3(dither), 1.0);
}
  `;

  useFrame(({ clock }) => {
    const settings = effectSettings ?? {
      animate: true,
      basePixelSize: 3.0,
      amplitude: 0.5,
      speed: 1.0,
    };

    const t = clock.getElapsedTime();
    const base = Number(settings.basePixelSize ?? 3.0);
    const amp = Number(settings.amplitude ?? 0.5);
    const spd = Number(settings.speed ?? 1.0);
    const anim = Boolean(settings.animate ?? true);

    const value = anim ? base + Math.sin(t * spd) * amp : base;
    const next = Math.max(0.05, value);

    if (matARef.current) matARef.current.uniforms.uPixelRatio.value = next;
    if (matBRef.current) matBRef.current.uniforms.uPixelRatio.value = next;
  });
  return (
    <group {...props} dispose={null}>
      <group position={[0, 97.279, 0]} rotation={[Math.PI, 0, -3.133]}>
        <group position={[174.737, -50.16, 100.694]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#6_0"].geometry}
            material={materials.Material_6}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#8_0"].geometry}
            material={materials.Material_8}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#7_0"].geometry}
            material={materials.Material_7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#9_0"].geometry}
            material={materials.Material_9}
          >
            <shaderMaterial
              ref={matARef}
              vertexShader={vertex}
              fragmentShader={fragment}
              uniforms={uniforms}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_02_-_Default_0"].geometry}
            // material={materials['02_-_Default']}
          >
            <shaderMaterial
              ref={matBRef}
              vertexShader={vertex}
              fragmentShader={fragment}
              uniforms={uniforms}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#17_0"].geometry}
            material={materials.Material_17}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#1_0"].geometry}
            material={materials.Material_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#3_0"].geometry}
            material={materials.Material_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#4_0"].geometry}
            material={materials.Material_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#5_0"].geometry}
            material={materials.Material_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#2_0"].geometry}
            material={materials.Material_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#14_0"].geometry}
            material={materials.Material_14}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#0_0"].geometry}
            material={materials.Material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Low_Poly_Rx7_Material_#19_0"].geometry}
            material={materials.Material_19}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Floor_Material_#7_0"].geometry}
        material={materials.Material_7}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/car.glb");
